import Navbar from "@/components/nav";
import { Card, CardHeader, CardContent, CardDescription, CardTitle } from "@/components/ui/card";
import { Footer } from "@/components/footer";
import DeleteBtn from "@/components/deletebtn";
import Link from "next/link";

export default function ArticlePage() {
  // Define the author name, date created, title, and content variables
  const authorName = "John Doe";
  const dateCreated = "July 21, 2024";
  const articleTitle = "Sample Article Title";
  const articleContent = `Lorem ipsum dolor sit amet, consectetur adipiscing elit...In the rapidly evolving world of technology, it is essential to stay updated with the latest advancements and trends. The digital landscape is constantly shifting, driven by innovations in artificial intelligence, machine learning, and data science. As technology continues to progress, it brings with it new opportunities and challenges, reshaping industries and altering the way we live and work.
One of the most significant advancements in recent years has been the rise of artificial intelligence (AI). AI systems are designed to perform tasks that typically require human intelligence, such as visual perception, speech recognition, decision-making, and language translation. With the increasing capabilities of AI, businesses can automate complex processes, gain insights from vast amounts of data, and enhance customer experiences. However, the rapid development of AI also raises ethical and societal concerns, including privacy issues, job displacement, and the potential for biased algorithms.
Machine learning, a subset of AI, focuses on the development of algorithms that allow computers to learn from and make predictions based on data. Machine learning models are used in various applications, from recommending products on e-commerce platforms to detecting fraudulent activities in financial transactions. As machine learning techniques become more sophisticated, they have the potential to transform industries such as healthcare, finance, and transportation
Data science is another critical field that plays a crucial role in harnessing the power of data. Data scientists analyze and interpret complex data sets to extract valuable insights and inform decision-making. They use statistical methods, data visualization tools, and programming languages to uncover patterns and trends that can drive business strategies and improve operational efficiency. With the explosion of data generated by digital devices and online activities, the demand for skilled data scientists continues to grow.
In addition to these technological advancements, the rise of the Internet of Things (IoT) has further expanded the scope of digital innovation. IoT refers to the network of interconnected devices that communicate and share data with each other. From smart home appliances to wearable fitness trackers, IoT devices are becoming increasingly prevalent in everyday life. They offer convenience, efficiency, and personalized experiences, but also present challenges related to security and data privacy.
As we look to the future, it is clear that technology will continue to shape our world in profound ways. Staying informed about emerging trends and advancements is crucial for individuals and organizations seeking to navigate the complexities of the digital age. Embracing innovation, while also addressing the ethical and practical implications, will be key to harnessing the full potential of technology and creating a positive impact on society.`;

  return (
    <main className="flex min-h-screen flex-col items-center justify-center pt-25 pb-24 pl-24 pr-24 bg-zinc-300">
      <Navbar />

      <Card className="w-full max-w-3xl p-4 mt-8"> 
        <CardHeader>
          <div className="flex justify-between items-center">
            <CardTitle className="text-2xl font-bold">{authorName}</CardTitle>
            <CardDescription className="text-gray-500">{dateCreated}</CardDescription>
          </div>
        </CardHeader>
        <CardContent>
          <div className="text-center mb-6">
            <h2 className="text-4xl font-bold text-black">{articleTitle}</h2>
          </div>
          <div>
            <p className="text-lg text-black">
              {articleContent.split("\n").map((paragraph, index) => (
                <span key={index}>
                  {paragraph}
                  <br />
                </span>
              ))}
            </p>
          </div>
        </CardContent>

        <div className="p-4 flex justify-between">
          <DeleteBtn/>
          <Link
            href={{
              pathname: "/update",
              query: {
                author: authorName,
                date: dateCreated,
                title: articleTitle,
                content: articleContent
              }
            }}
          >
            <button className="px-6 py-3 text-lg font-medium text-white bg-red-600 rounded-md hover:bg-zinc-400 hover:text-white transition duration-300">
              Update
            </button>
          </Link>
        </div>
      </Card>

      <Footer/>
    </main>
  );
}
